apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-minio-credentials
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-minio-secret
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: secret/minio/keycloak-db
        property: user
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: secret/minio/keycloak-db
        property: key
